/* soapServer.cpp
   Generated by gSOAP 2.8.14 from getIp.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.8.14 2013-02-28 12:53:44 GMT")


extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:GetGeoIP"))
		return soap_serve___ns1__GetGeoIP(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:GetGeoIPContext"))
		return soap_serve___ns1__GetGeoIPContext(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:GetGeoIP"))
		return soap_serve___ns1__GetGeoIP_(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:GetGeoIPContext"))
		return soap_serve___ns1__GetGeoIPContext_(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetGeoIP(struct soap *soap)
{	struct __ns1__GetGeoIP soap_tmp___ns1__GetGeoIP;
	_ns1__GetGeoIPResponse ns1__GetGeoIPResponse;
	ns1__GetGeoIPResponse.soap_default(soap);
	soap_default___ns1__GetGeoIP(soap, &soap_tmp___ns1__GetGeoIP);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__GetGeoIP(soap, &soap_tmp___ns1__GetGeoIP, "-ns1:GetGeoIP", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GetGeoIP(soap, soap_tmp___ns1__GetGeoIP.ns1__GetGeoIP, &ns1__GetGeoIPResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__GetGeoIPResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetGeoIPResponse.soap_put(soap, "ns1:GetGeoIPResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetGeoIPResponse.soap_put(soap, "ns1:GetGeoIPResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetGeoIPContext(struct soap *soap)
{	struct __ns1__GetGeoIPContext soap_tmp___ns1__GetGeoIPContext;
	_ns1__GetGeoIPContextResponse ns1__GetGeoIPContextResponse;
	ns1__GetGeoIPContextResponse.soap_default(soap);
	soap_default___ns1__GetGeoIPContext(soap, &soap_tmp___ns1__GetGeoIPContext);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__GetGeoIPContext(soap, &soap_tmp___ns1__GetGeoIPContext, "-ns1:GetGeoIPContext", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GetGeoIPContext(soap, soap_tmp___ns1__GetGeoIPContext.ns1__GetGeoIPContext, &ns1__GetGeoIPContextResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__GetGeoIPContextResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetGeoIPContextResponse.soap_put(soap, "ns1:GetGeoIPContextResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetGeoIPContextResponse.soap_put(soap, "ns1:GetGeoIPContextResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetGeoIP_(struct soap *soap)
{	struct __ns1__GetGeoIP_ soap_tmp___ns1__GetGeoIP_;
	_ns1__GetGeoIPResponse ns1__GetGeoIPResponse;
	ns1__GetGeoIPResponse.soap_default(soap);
	soap_default___ns1__GetGeoIP_(soap, &soap_tmp___ns1__GetGeoIP_);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__GetGeoIP_(soap, &soap_tmp___ns1__GetGeoIP_, "-ns1:GetGeoIP", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GetGeoIP_(soap, soap_tmp___ns1__GetGeoIP_.ns1__GetGeoIP, &ns1__GetGeoIPResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__GetGeoIPResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetGeoIPResponse.soap_put(soap, "ns1:GetGeoIPResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetGeoIPResponse.soap_put(soap, "ns1:GetGeoIPResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetGeoIPContext_(struct soap *soap)
{	struct __ns1__GetGeoIPContext_ soap_tmp___ns1__GetGeoIPContext_;
	_ns1__GetGeoIPContextResponse ns1__GetGeoIPContextResponse;
	ns1__GetGeoIPContextResponse.soap_default(soap);
	soap_default___ns1__GetGeoIPContext_(soap, &soap_tmp___ns1__GetGeoIPContext_);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__GetGeoIPContext_(soap, &soap_tmp___ns1__GetGeoIPContext_, "-ns1:GetGeoIPContext", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GetGeoIPContext_(soap, soap_tmp___ns1__GetGeoIPContext_.ns1__GetGeoIPContext, &ns1__GetGeoIPContextResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__GetGeoIPContextResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetGeoIPContextResponse.soap_put(soap, "ns1:GetGeoIPContextResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetGeoIPContextResponse.soap_put(soap, "ns1:GetGeoIPContextResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.cpp */
